DROP TABLE IF EXISTS RATE_CARD;

CREATE TABLE RATE_CARD(
	ID VARCHAR2(36) PRIMARY KEY ,
	CATEGORY VARCHAR(50) NOT NULL,
	AMOUNT NUMERIC NOT NULL
);

DROP TABLE IF EXISTS METRO_CARD;

CREATE TABLE METRO_CARD(
	ID VARCHAR2(36)  PRIMARY KEY ,
	CATEGORY VARCHAR(50) NOT NULL,
	BALANCE NUMERIC NOT NULL,
	NAME VARCHAR2(50) NOT NULL
);

DROP TABLE IF EXISTS STATION;
CREATE TABLE STATION(
	ID VARCHAR2(36) PRIMARY KEY ,
	NAME VARCHAR2(50) NOT NULL
);

DROP TABLE IF EXISTS JOURNEY;
CREATE TABLE JOURNEY(
ID VARCHAR2(36) PRIMARY KEY ,
CARD_ID VARCHAR2(50) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
STARTING_BALANCE NUMERIC NOT NULL,
CATEGORY  VARCHAR2(50) NOT NULL,
RATE  NUMERIC NOT NULL,
DISCOUNT NUMERIC NOT NULL,
RECHARGE_AMOUNT NUMERIC NOT NULL,
RECHARGE_SERVICE_FEE NUMERIC NOT NULL,
END_AMOUNT NUMERIC ,
START_STATION  VARCHAR2(50),
END_STATION  VARCHAR2(50) ,
START_TIME TIMESTAMP,
END_TIME TIMESTAMP,
IS_RETURN BOOLEAN,
TOTAL_FAIR_CHARGED NUMERIC ,
IN_PROGRESS BOOLEAN,
FOREIGN KEY (START_STATION) REFERENCES STATION(ID),
FOREIGN KEY (END_STATION) REFERENCES STATION(ID)
);